# Spring application config
server:
  port: 8090

# Variables for the application configuration.
application:
  interceptor:
    paths: /any-path
  constants:
    headers:
      - name: example
        description: description of header
        methods: post, get
      - name: getexample
        description: only get
        methods: get
      - name: Content-Type
        description: This required in the body request.
        methods: post
